build-steps:
  - post-build:
      type: script
      script:
        - rm -f /tmp/version_check_failure
        - chmod 555 $SOURCE_DIR/check-versions.sh
        - $SOURCE_DIR/check-versions.sh "php" "$(php --version)" "5.6.29"
        - $SOURCE_DIR/check-versions.sh "acquia-yaml" "$(gem list acquia-yaml)" "1.0.4"
        - $SOURCE_DIR/check-versions.sh "composer" "$(composer --no-ansi --version)" "1.2.4"
        - $SOURCE_DIR/check-versions.sh "ssh" "$(ssh -V 2>&1)" "OpenSSH_6.7p1"
        - $SOURCE_DIR/check-versions.sh "rsync" "$(rsync --version)" "3.1.1"
        - $SOURCE_DIR/check-versions.sh "nodejs" "$(nodejs --version)" "v4.7.0"
        - $SOURCE_DIR/check-versions.sh "git" "$(git --version)" "2.1.4"
        - $SOURCE_DIR/check-versions.sh "unzip" "$(unzip -v)" "6.00"
        - $SOURCE_DIR/check-versions.sh "bzip2" "$(bzip2 --version 2>&1 | head -n1)" "1.0.6"
        - $SOURCE_DIR/check-versions.sh "gem" "$(gem --version)" "2.6.8"
        - $SOURCE_DIR/check-versions.sh "npm" "$(npm --version)" "2.15.11"
        - $SOURCE_DIR/check-versions.sh "drush default" "$(drush --version)" "7.4.0"
        - $SOURCE_DIR/check-versions.sh "drush6" "$(drush6 --version)" "6.7.0"
        - $SOURCE_DIR/check-versions.sh "drush7" "$(drush7 --version)" "7.4.0"
        - $SOURCE_DIR/check-versions.sh "drush8" "$(drush8 --version)" "8.0.3"
        - $SOURCE_DIR/check-versions.sh "wget" "$(wget --version)" "1.16"
        - $SOURCE_DIR/check-versions.sh "mysql" "$(mysql --version)" "5.5.53"
        - $SOURCE_DIR/check-versions.sh "patch" "$(patch --version)" "2.7.5"
        - $SOURCE_DIR/check-versions.sh "nvm" "$(nvm --version)" "0.32.1"
        - $SOURCE_DIR/check-versions.sh "rvm" "$(rvm --version)" "1.28.0"
        - $SOURCE_DIR/check-versions.sh "rvm" "$(rvm list)" "ruby-2.1.10"
        - $SOURCE_DIR/check-versions.sh "rvm" "$(rvm list)" "ruby-2.2.6"
        - $SOURCE_DIR/check-versions.sh "rvm" "$(rvm list)" "ruby-2.3.3"
        - $SOURCE_DIR/check-versions.sh "bundler" "$(bundler --version)" "1.13.6"
        # Fontconfig version command is strange so we check for a blank string.
        - $SOURCE_DIR/check-versions.sh "fontconfig" "$(fc-list --version)" ""
        -
        - echo "Checking php extension versions..."
        - php $SOURCE_DIR/check-php-extensions-versions.php
        - # The PHP pcntl extension does not have a version string.
        - $SOURCE_DIR/check-versions.sh "php pcntl extension" "$(php -m)" "pcntl"
        - $SOURCE_DIR/check-versions.sh "php bcmath extension" "$(php -m)" "bcmath"
        - $SOURCE_DIR/check-versions.sh "php xsl extension" "$(php -m)" "xsl"
        -
        - # Fail this test if there were any failures.
        - if [ -f /tmp/version_check_failure ]; then
        -   echo "Failures in the version check:"
        -   cat /tmp/version_check_failure
        -   exit 1
        - fi
