build-steps:
  - post-build:
      type: script
      script:
        - set -e
        - chmod 555 %SOURCE_DIR%/check-versions.sh
        - echo "Checking php version..."
        - %SOURCE_DIR%/check-versions.sh "php" "$(php --version)" "5.6.14"
        - echo "Checking composer version..."
        - %SOURCE_DIR%/check-versions.sh "composer" "$(composer --no-ansi --version)" "1.0-dev\s(a54f84f05f915c6d42bed94de0cdcb4406a4707b)"
        - echo "Checking ruby version..."
        - %SOURCE_DIR%/check-versions.sh "ruby" "$(ruby --version)" "2.1.5"
        - echo "Checking ssh version..."
        - %SOURCE_DIR%/check-versions.sh "ssh" "$(ssh -V 2>&1)" "OpenSSH_6.7p1"
        - echo "Checking rsync version..."
        - %SOURCE_DIR%/check-versions.sh "rsync" "$(rsync --version)" "3.1.1"
        - echo "Checking nodejs version..."
        - %SOURCE_DIR%/check-versions.sh "nodejs" "$(nodejs --version)" "v0.12.7"
        - echo "Checking git version..."
        - %SOURCE_DIR%/check-versions.sh "git" "$(git --version)" "2.1.4"
        - echo "Checking unzip version..."
        - %SOURCE_DIR%/check-versions.sh "unzip" "$(unzip -v)" "6.00"
        - echo "Checking gem version..."
        - %SOURCE_DIR%/check-versions.sh "gem" "$(gem --version)" "2.4.8"
        - echo "Checking compass version..."
        - %SOURCE_DIR%/check-versions.sh "compass" "$(compass --version)" "1.0.3"
        - echo "Checking npm version..."
        - %SOURCE_DIR%/check-versions.sh "npm" "$(npm --version)" "2.11.3"
        - echo "Checking grunt version..."
        - %SOURCE_DIR%/check-versions.sh "grunt" "$(grunt --version)" "v0.1.13"
        - echo "Checking bower version..."
        - %SOURCE_DIR%/check-versions.sh "bower" "$(bower --version)" "1.5.3"
        - echo "Checking drush version..."
        - %SOURCE_DIR%/check-versions.sh "drush" "$(drush --version)" "6.6.0"
        - echo "Checking php extension versions..."
        - php %SOURCE_DIR%/check-php-extensions-versions.php 
