version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH: "THISVARIABLEISDEFINEDINYAML"
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "passing job"
          - exit 1
  post-deploy:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "passing job"
          - echo $COMPOSER_AUTH
          - exit 1
  fail-on-build:
    steps:
      - check-for-variable:
        script:
          - echo "fail on build"
          - echo $COMPOSER_AUTH
  pr-merged:
    steps:
      - prmerged:
          script:
          - echo "pr merged"
          - echo $COMPOSER_AUTH
  pr-closed:
    steps:
      - prclosed:
          script:
          - echo "pr closed"
          - echo $COMPOSER_AUTH

