version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      secure: 2acZ+7Jji6N+P8/sItKDk9FANNv7lmP9yG7Fys2xkPSqNAvhP6M4n9FtQelJ68ea0LggzzjYTDtJtnsvw562RB5DO/Tgq8xanFrbq4enP3rqCSB0mCpEJ2OXeTDsUQ9H35o42YD9fr8Q9Qu7C6xTD/TLtcXYNa79sJi3fI8C9pVEqykQiqaotYOg5lONaYLK+xvQHsMZ7GwUpSSnlPi5dMcAcRWMMHLcfoyeaxH6yJU680G0H4nMkLbyzVZwOUwOzRkNZH+NhziaHyXo+3ggLnSC9tlS0IPV4BrBfpI0XvqBEt4m3D1J1wg34omHTKeFRNEd+YjO/N8+BIX1rGY+sxbSiNDWl1CFD/BUTADBCu/HiyBDhn5KS8fcTuvkI2d7c8F4umnMYGwwwxGAHDqtq+y9vERyz3QIWVS+oPWHKjY51OkETX/3eXUF2E2DsM0BHAbszbGy3xb6ToNMEizlfxXA6EmaUN74UoAOdYUFQ1xHrOwOQfTJ/vpKcmNq5A+/albRdpaSAv7gRA/ChJFW6ziXY/X1SgsXkx9F1rjuN6dkw/UblZ44OeAUqntIVtiw+X1xecVKGbknLKpxMz8RKMuvsB59772/YQF9S3dVwp6sULY53T4nXwzgI0KZVPuG748cUGWkvrEBYS6kw8MnIaaj8EjyAj/dICW+UnbmMCFirI=s5DHRCcfW/EV48ew79jwdQB/DnsG/GuCbvjWx4Qu3zHMGanUQSyBggR1DHtZjRTLhayISr7vTOapSySfdWoTbx8/C6IQhAUGE69WBZJFOS3KFTRt16wzKCfS5smIsq45r8G9s1l6FKAuSZlNX/RSy65YgPcjj0bfrQKoAiatS33IAZPi8uKw18mZJqrhJ3KRUM4j8pbuY8CbxN8KzU8f8nmtlHmLfitw6E/3KbaO6WQ=
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
