version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600

events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "passing job"
  pr-merged:
    steps:
      - prmerged:
          script:
          - echo "pr merged"
  pr-closed:
    steps:
      - prclosed:
          script:
          - echo "pr closed"
        
