version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      secure: 2acO8z0CQmhv0LKqjReAXzCJuN91K1iVHeiaBHVo+42TpH8OXicQkcvVlNv+eO5cAnmmz/zfN+cLMg78FX+k57fq0brF9t1yGhc/n/sNIunZVe9znqn9lomFXA/aBfJKlvpZO5JBCuOlHQDEw33WQUWSoKEPLAfykxWH/xb+QO4Pqe6K0TXnuazE0ZZdJQjZvCX+T58Qsm/xYZO8dsaNyjDLNaVfmJL2PhUUo7+6rQinHmh9bCGrnzj456vxNl/sZSjTPHfQaV3PAkt3qZ4zp3XZp/PgKj9LVMuplVSkpJzBpLhpv+HTV86r3N3fYK1D67GFe2lA81w1R7gHlRZpe0qMhtyPINz0UANXQM6Pn19uHPeFP2DjBW9PTWPUPBiOyv1fx488bw1snAO1U5DDJHlqxYjgubhqQbENdwTc5UjKek5yNgy9T787hTdNHerVYMyKROKU13WEbT6iQpr072/OLaqSAQxQUm+17waNUwCIcSCfcDJj8xaoTzNyFz1ZF2ibKqxkF0933Q/EFQDPr6XJ00CF5Fy/2MZxjImW04CH7RjU6oMeimPkIFEICMTzpTW1FxJY5GoocMhNkML2syb1jMaNXYrJKZ4b6mj4xvRk4Q6YAWON0LHJrVgfZsh+gq0VKia1K8/E+pREehWN3+LFObPMWK4iZHBYqjeAZ2OjaE=r7A4YablfxNgsL9lyHuHz43orHqESXN6GBvsWl42RAjxRcoNUlx0x1Zx450iYNC6N7lqKCN6pKLLCJbKQvutQIhT3SwBs/rC/2q48fZJiFXYjoG20yyb68OZLjvER5MPbdwwaxe27C4OdOFSCrV+2fbPFxTsfX8C6HT6DUlDzA3asCiBQUwrTnTDk/EhbpiXL+b0UWBmMKQ66OaSIduEvTojans3XaLdQ0LOpywTbH3TNeSLUAjpcYsruwQI+wlq6wa+fsMX8lLsl3wgJIqIwT58XLS2PYZa6Fk31Rp7SJI=
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
