version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      #secure: 2ac0nfX944Szo8oZSoWh14OQIzs5yquEqHKp4w7ZSd7ox0GxOQhjnDikRQUuXUAFVCqxMwh/woqHk5wXlCs+i5JmCnuaZgRkhQhgmCxytgVrdwO71nMJDw6lnUv//kr26l23eFX6wcKXfaHGXB4pZMf6yik4BhHF8RXemNpoU103DYqCRA/IPUEHY2PnGN6fW1tjIFS/aOJQcf293Xv9V231o16h4IFPOfh60RO3GqwACrnyDFrG5MdkwT2uEvJp0DcXekJwsk+mgpFFEgvw1/FRo9wQOfTArySIQtedYBenHD7nBuB/16bELbuKUoe8QD0Sp/QBJgyBoY6LANCz4PQRs10kk8zK6fGcKLDLNygMcQm2XLHspb4xgLC4023nqztfCocVIElp2ana1fc9kU7pAwx67g8iOcqWFjXH2bgKl4ZslNnsYcZtbfwRi1PfXiLqPI7kovWt4rlgmgp2IG9x1iMHKXlsQI1eP2GY+UZLPcmmoBUG9KocNvZenUTmaPQTkhWRv18n8p6L/Ryv5eTMawDnbJfAG+A+nt4HW3w2rOpUw1FS2Stz/bCPoeQegqawFS2OOo3dfkMNtYu+OzNssepaMWcMVUq8VzmqXjxc9reTJwf2YxBUd+WaMNqoR/1GqzdmI9JYTsMeIzMOQxkU2qzXGMHO1DPqhMaVeCN5kE=G8uwUf76nNpWmfZm37GEnb2iVhW76MZodkCguAz3dGP6UNlv9EygFSS3rK9XRiIADtFkdAH8B/aowHVqPhf02HmnYFRdse9ADhUp9ilWGMNtubi5RqsaceD2HvQ6VGZJxFUSNwW379J2/XlSNHSOtE9DIsA91dnKeqyxRAWTZD6904RxRFQqhumJhbtvP4Z3l+OJVbFcad0PH+GNvA7zzR2udqBKrbZkWM4E72ZWtFtU51axOzz5GP9XBC0T11itVu84qBA5yYRYCZ+qZN832Q==
      secure: 2acY8IL0QIhmVTTxC7mXOzw6m6qtONJc4NTX4eP8nxsr/hBSgX/Lfv2PMMBntSdo9AmlRGVLV1JfiVMoWQM5sBkS4m0wTLJcEewsubFJ9C9/WEksCw3jcYkk8EvvB0ECJgc1JPI/ZUptwC2nE98o8I51rAf2rXFvnOH9+ZB8EJ3ZoLVNKFvll8tN9+FmHD9dhssxnWVvskrxCMfalfUyGmpyD4ds6ke9CY5ZTlOEKaxt781kv5l9z7dkhqk9AWT4pykCG1vGV/Uu+MIjettET4FxCTQoZztUwfrxFNBbEHXsMTDCm12/J4xjgxr8E7UWdJ5RbH68ZtWbWuZXNUxX4zoxYDY3wBQP+K48jqWJ7uW/dIMkfyGevLYqhcuP50SqKkyBff/qcqWwDr9713WE4knA4t7un/6FmmS9GERP8tG9mf/chUwZpY8R75zEa1Hs+7wneCCu6yE2xnvsqNqD4vKdF1EcJ0TirZqONYJvxquKGZH6f0GvGs47jPjw53vie+91B6bfyFRDstWY0Qm93xIcJRRc/a+IhCpz4PMXERoSHfeHrpO22/Yeu8svNayaCUXXhK/AnsIxc8X+Pss4Hk62UReF0vPeoKFQlcY2QRursntStP3Wn4zZuB63lbmSMa1yZOifjl9SBYnL0R5xyB2o2sr7M8OMo6nsEzulW1V0b4=Yh6U6bZJzg3oJ0fSwpImloyGi+dBAiRZXIZ0lMFYUPJtvPxWXZPr3LH90EJzDbyYWv5yJFOX8JpqiPQ8jpK9XSzVKHNy/JYRfmfKiuyfR0ll9kvH//bRhnDTk+33VgNEbFGJLoE/EZ2VvSc585pWgRqbSHEW9FLu86gTjUywB0ETXhD7G1pJF1qbco2RE+OXrcFV7jJx3U2G8aCaSnblBFOnkQ1n/kt0F4Ca/P2tmbFc+DBZHog7ZfsyJQU7HGoQLQxvmh8nQfTwHGGsw/VHQg==

events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
