version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH=:
      secure: 2acK0p1GDxr6Bv48+IvZejodEUnOwFimWk+7yjxS1DDShR9JqjENetwCvBXe/dYy9UeBvDTZ6l61EZznpiPkUpC55Mef/TgAeeqd1q3j/yL5Tf/Sgk4RSLdjk2SwLyVeo+zVlFd1foRyHotCFkqb5ASrt/yjTUmhGy1NZdUYxldMCncaNq6P2mUzdkVvQYfsvVfCDN43azv8CJbjuxXsWkv4RlaWImEm84qoT/5ubjbR7ywT3GnpbzPd2K/hyWCd3OZpbFsmws+ExrRsxXooHkGzaF/tD6pF5ecLElO7GjrG7kyAZqjL+92DeH0BwYipRtdOtsp+/Yke9v3ZXcJjv1Z2b1zXmGWmuOYwCznCcVNPgCyvxezcYUMlsfpP8WIMytVVsIBLOxlWJYkXrnHxmpfPtCMAevrRtG0EWw4N/Z+H0wOaYYemzteoF4DH1nXoWw9j3sor20M2nQLOvvmmpaq8EbBuSiYnmTtkXQ/7iu/yp5gQ3PMWipLVTvWSzRsLL4LuTfXzXoLg3otAGLVqFJTYg8BvgiHA3qKpd1fTrjWPG1AizzkycdlhfaQGQMzb1/6mUjxIzl8IqhJJkpBcmXIL5Ime/CfUrZbgpKFI/jhlGdqc58r+agtRPMjzofncMviaa7lpQHf4Y64xJfDPTrtMTvAwG6xFl3Qt8qBtt4v8BE=WZHcj3cL7xKPE/xwzo4mjtbhuJrSau71niGrlS9L2wYHIS1rSQVL7QfogoFvuecMg09ZYr3m1P8IT2IV3QW/vaJ7lvMnbSXfMkmHjifocKsJZvK/HrrYvS8fKoTCCcSozvSjbwwtInFOjAUy0FDzhx0529MTiV0XVEW2qGs8N1kTkzXQefz/sJLvDaKS9/GYOMr4BE09UvoxGbglLvaUP/nFvaqapTyLgB09x/fa9ptyZIz6OUjz0JdWIwHdwLEY6YEwBVih6on8cV1UYoVTEwe9nrjq1YobaYUcOCoSmIA=
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
