version: 1.3.0

services:
  - composer:
      version: 2

ssh-keys:
  gitclonekey:
    secure: 2acfGebwpSVXLzpYsCtOmvtsTJTrh7MPOhFWMzRRSEU5HfzKSUd2mfaCZNYNSyU3eCYIrGnzRmG/UrMr5aUHNGIEaAt3TU44JzsbUyDe+Q/EPCfgn55NsiEtmrXi+2xHuzY6tKAVNwrhDIw5tPPPa9UVIQb1er383fN/QDDFFEbWBDDQgrIk+bOq9XrPt7bP7WIuWBj/oPYYj/EmSp5DQNfkp4bRJRBY4xsifIZujF7BDGy9ecVgeTeb9aUVu7kEQcryF4Vcr3yZvMF+He28oC2uPnTOoUaTLfTctSID7Qih1LpwgwkxnuMDqy6EDTrDyTzYExywb7hzzNkl5s2dqGXWQKz6uUX3ei6cSn1hkDDrhqrFvsTygpicpKEkXXsl7gI1dZV2pKrCCR4othECQgUVO5d+Z9eyTmzEq9LOIE23yisUnBpKnP4LbkECIf35bV46DdgC/ht+gGuI3go7MOswv2pLf3FFLQIWnTMRtCKnwz+k6O6QESsFctdfckeIw87YuxLv4TsRSR8wcW/KgvuNSuKcedGr3k1XY5eJw2HW5rpn8WeDe9yVsXvzu459SwH+R71rIIA4kfeluameZunrRbcJohstCjGtKQLu3tFm8FzXKw3hZX/i9JLB67jgxt1jAwez6e0p4zbzaKJ5VNZOIDVktpdCaXZKuI4oQgeg60=JrGBzSnnigMCmpUnWLZk5Erx4c6rHx9L3Ncw8is75adHoZ11Vs6QSJZrgN8mSxy80QaDRpVUtQsuI1Fn2aGxeDfo6btV8bUeIH5VKIWZfGkpbHfV/o70h+d6fScJRW0hd+R0wYXNe4JJxhvp66N+W0MYwfyObdejta9GE4f0la533XAwD4AS9Bm9kT3zj5zHNMDPEmyl3cA+CagYLxX+P4LoBZ7BXEM25owLXJ2a8adSsxQR5ir04iWIob1NneWgqjXNypZMVHVmrNifWcmDWC1+r8CYF8ZcQa3PjLMt/xlGiQzloKSOvKuvMYuQT5pbsd+Ej8UyOAwKu7WbQohTqEgj57oLFmNmkzTt2hpki1Nh/omz7TesJxtlNbzqM8rSyjis8Yemv8uBTXzSmarZfCs9q+WqaJGUm3C6o5KI1A3aB769VZCJCp72EfW5Y+Pkz/sngRD4y7DdgwP+PJQaYdcxzAKnfDpxYf69u/HQMlZ3NrfMOyNLQm0QpPP/RCEw8U+jcvVTKhTkwcuLww5UhwFnQ3oTU90wimRhkbPZsibLcAu/cNss3enI2wdi3W2Ymx7mkef4Zj8qMnViKFrWFAIIuxIaElctUP4pFENHoap5SGyha6ofQWhWGFgii+9jPt1ugEWNDpeVeSLwLTTQD1Ojv1Ba4iFknlZUdYLIOkQ53iBBQseMzK7VXUkM0OM5

variables:
  global:
    COMPOSER_AUTH:
      secure: 2ac0nfX944Szo8oZSoWh14OQIzs5yquEqHKp4w7ZSd7ox0GxOQhjnDikRQUuXUAFVCqxMwh/woqHk5wXlCs+i5JmCnuaZgRkhQhgmCxytgVrdwO71nMJDw6lnUv//kr26l23eFX6wcKXfaHGXB4pZMf6yik4BhHF8RXemNpoU103DYqCRA/IPUEHY2PnGN6fW1tjIFS/aOJQcf293Xv9V231o16h4IFPOfh60RO3GqwACrnyDFrG5MdkwT2uEvJp0DcXekJwsk+mgpFFEgvw1/FRo9wQOfTArySIQtedYBenHD7nBuB/16bELbuKUoe8QD0Sp/QBJgyBoY6LANCz4PQRs10kk8zK6fGcKLDLNygMcQm2XLHspb4xgLC4023nqztfCocVIElp2ana1fc9kU7pAwx67g8iOcqWFjXH2bgKl4ZslNnsYcZtbfwRi1PfXiLqPI7kovWt4rlgmgp2IG9x1iMHKXlsQI1eP2GY+UZLPcmmoBUG9KocNvZenUTmaPQTkhWRv18n8p6L/Ryv5eTMawDnbJfAG+A+nt4HW3w2rOpUw1FS2Stz/bCPoeQegqawFS2OOo3dfkMNtYu+OzNssepaMWcMVUq8VzmqXjxc9reTJwf2YxBUd+WaMNqoR/1GqzdmI9JYTsMeIzMOQxkU2qzXGMHO1DPqhMaVeCN5kE=G8uwUf76nNpWmfZm37GEnb2iVhW76MZodkCguAz3dGP6UNlv9EygFSS3rK9XRiIADtFkdAH8B/aowHVqPhf02HmnYFRdse9ADhUp9ilWGMNtubi5RqsaceD2HvQ6VGZJxFUSNwW379J2/XlSNHSOtE9DIsA91dnKeqyxRAWTZD6904RxRFQqhumJhbtvP4Z3l+OJVbFcad0PH+GNvA7zzR2udqBKrbZkWM4E72ZWtFtU51axOzz5GP9XBC0T11itVu84qBA5yYRYCZ+qZN832Q==

events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - ls
          - echo $COMPOSER_AUTH
          - cat ~/.ssh/gitclonekey
