version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      secure: 2acgV7xvFw4yJ3OpTy5/eYWnAlDXPpkCYNlrz1HAJ7S0q3cX2jM1vYux/kRO8/WYGBkbvOrQ3OldIflZAadJ61wdW2Zefu6PbMsxTfyCLPysGCU7QRfphzZnm1uzQ3HoUAPOzsohhYtHgy+ZbW/F53U5Q3003jpp/Boowf8O6SwoK8mJ4nmgWIzNZnEAfFMAPY7gttwKXmiF39t0v/StZVH26IoqLskE4xLuWiRWfNzXcDaI3wohDozuJ6fZT7vFb3MgXBUYM6iiJ5jyDl4Io1rV2JrFO1pJ246kIRKB7IyGjBjPu2SpixU8Vo1xJue77UZzWRDWexY6e/jxzxmNgoydtbYfRt915KbjLHMcF/+ZMWVA+Lg+CYfGmvDj7NCbhKzDpbSeOD6qJUnRB7RCSywQgI0PASEVD6qSWIyLc0A8FfIEf+rSnOy2/vkMJpsd2Su9Y9fXJt08w3LwHkBNUOymAyyBzmnCnW8nrYD80vqcYrB4I3wh1n7sdDvTfdqw/CXuiAnR/dr8NgeEBlVJqS1F0Y/gDbE6c1cH2kg5y2gCfdKECVzLrb935I4HM8tDQdE5xrA0Tti7zqmwEVybUneiyGEWpe43Q4wuO1OInppkM1J6lKQihX6w0k/XTIC/arNJrvuHS+gEQo0UqwEXkmxDgsstK2/OwDx1zbDrFlHRd4=k4yM8WbngkU25ayAUvnD9bTWr8cQxt3cKgzaKcUAW9AZlxpQclfKFk1WyXUxGG8QHU7FscTCd57gJpx+WaSMoU8K3v1Tn4ctHHmy3XPvz3Pv5dNxS9idnShhNEOV5c5Qrc5sxy4R73W1iUiJO9Ub8z9xHRTh+TLbywOAyHweo4OY8NoFMP0UhKAr8dBjA7Pc4bbgFTZvEwo5c4M0M/J4a9pmyEzpfOqXE3jAUjQ/zoOgsiFyJww9q/+TSuU3ggN7NZs+OHsP/qsyXHpDzLV85myMwDeMLKjRjMAAFR4ajOA=
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
