version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      secure: 2acjEsot/S91y5fVz81i8kc/P5igkFLle+A0UrOd3+RYus6E8WMr2wrRTXwh52n8UBA65WgTkR2C/ZY0PNZJmX2WktxlQQJv1q5wt+oj2BGF4Hw6Aq+4RWU+1ONNSCqN/NMb5PmqNCMTtJSj5npEeaS/PRfJ874WRq7EU6PO743s36GtgE3b/gvViGw8QSZ/vrSL4+sE2nrsbbvwaB5QHKpkIsSTa+2TKazv03y9TpIvzjg0VkPHQbftQTuHUOsWeXB5HKPrQL01yTlKEcds4YbBxmwlTt3p1eO3czrSAGR7emZuwMnQMz+wtDfQTaQZu9FxSqAL8ljC2rysasVuhQI9aC3V8E3OKJ43i1kHSbYWEzNoW55Weagt3UD1lMRhhbPij+T+N3wqiI7g+PL+kyeStcSIqUmJn6GHVhlHsX4du8ZX1eeN9m7At28J4hbNDfKCijSBJ+TwTNzaHN6aYIN4Udk6uDd6kRZrRPGQImy1WwGznIEG9v+8+sIf0Bx9kOXNYOSn7/l1EZ8hePg0WBki++Sn0JB4H9XZrHS6qFhosyPtxLFYO5jybgyf3WYCNqaDctqPqc9ppCdbd62T+mqueJqP1p6/RzvAcsf+WQcsykJpMfgvdZl60a8Pq7tXg5Ca5hCiUbaYO1EUpthkfwroAMFPA8x4x2f3SHdnGACXf0=XWaPXci4/cnmL6pO/Tj3zCD7C8R81X7yMNcrG5D47DokGO48fPIAHW5IbejB35VcyIMvG1KmtuYMbvRhyGrm71Noy/x59H7PV+1/2q9RqMMGotQvfRW5egVSl3DwtlcKrwj9w10IlyWKReACpcYQiPxTPQcelqx8DlR0TYflA/PviUhUoEG+bvj12Hp7NSDOiT8d0B0qkQ+m0p0sRqUFpNlw2LPkpIOuwZ4G88dkwWJBGuZIp6zD1D3/G39rl1JF0zmoSQOqnXKWyU+QDftiB/O4MIHrrse9Z1T2tCDMWNw=
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
