version: 1.3.0

services:
  - composer:
      version: 2
ssh-keys:
  write-key:
    secure: 2actTPYs4FnR3UqoJt5pP6GuNXdD3+fADdF5tQpIH4yYkKu3d4HxQVAJ37rUBvdJ8VnOdpjE3+yGFPoddOGETOCQb2KbdqXI4STvQPCtyOwoXhbS6dhpy44PY8QU8Mj7JshzWti6/FFRI7iIlvBXDKeyZ1vTg95Hhs8yzJd4xDVHKk+F0uMSX8HTbzgObCVMxN9+1uHpqAW6Do1tOSjmPdPxjn8+P/qi6ttGtWTVRStxuR+hOv5vsrCBni04mIerDC7AHkc+zyL/K7OOzE+XdogAuLytgRR3+kkyWGrlWT7JXenfLaNteX0oDt8oNCDFQzrzH6Rm1aHGlRl21KRc2QBfTXNE7KZWLvyHLEINT26moBL/YYnSW+aPV+sM/quVG36MqNhbEazfhTiQ/aatYKbA2Y+NTttKEwZzKwiEuq+tlaH4no16WmIx0zXFbQxpFLRrnAjFOhNAsBJEGRaO6Q/j8ecz0jxxouMlQ9vHMt9TJ/Yj06kvX/reOL3trXGq9MSYoKHuwuB6UcB6WO0Z88TcuZVhOCJIVUs1z+tij9eeT+W0vy4dAovnLgmhBsSevLp7v8ttr0SUJiefJzDVDXxMoarUQK4uKm9lsEnnWwfNhtVQJxnAm8VIdzqmnD2rw4OcTxhYjil5s/YMwDpl5W/anJLm8TnH0bVRah7OFnynHY=/R0U2ncxJo5HqECLuqhAMpQXjEYEoCw6g/6Zw+RE9wqMovo+j0cwPFdKb/c7i3cF/tgNlBJSYktMhhsJulSfDPtKdz1onJD5zQsseQEKZw6TPnEpL5wu5q6L3HA29Cv224qzbiGC5InXQWaW7H5MFkaHXVvofBAjWEVS8SJhyYMwhk7BE8WUQ9ko2xjGSFfMbHFFG96UDgKCRB0wp/V9/oc2d+YWrsIW0gh7/ldzV+ScRW22DlkaQKbOf1uFGBZLgBhKp7LHhTnVxmhIeJ/UHUWvb+6QWi/ojPxOm8mD/kRfixP2XJ+0Z9JAbdY0+qkNk/LgdAwmkiXLRYf7HQllLWatAXljKiBPHpoBK2gZd7rlCMkqKXyXvkD+PM4E6OtnbeV+IKgu5M9vZfa0AWHBCXCvLD62OMMOIMSOmibRLRgMHF4BzsUJssFxo1+1L5/V9q8g5lOomTZmHsLfteWjBYmsQA/U+r8cW32+bmP+vga5I/yLa9xFZmvWojW2FmZWSBl/PYRaSC3gJ2CI0B4xzEnZLacSseRp9eoW9peRnP2tVWnGWA9PP8rBEpmAyvt3Q+NZNRUxA1Waj+ddVQfUEsJ4SvL9a73I0uPhpilY1ia79LyGi1nOydt7yO0hzwyoBWGFeD3HNnUjLR5LNj7BB6pr5n668akXF9xIJEL/HXA46VFkz5GXTE8w9PagjUlZ

variables:
  global:
    COMPOSER_AUTH:
      secure: 2acchsQlFRvFSj/Nv5E+72l2U1ZvjeTMhK/yrald1+l4j8GeC2C5HH7N9l2V0SfJTfWxkWxX4UQmuD+crPMu3G6Q/Q+5+AoKphFX8VfNfoJnwVj8kOyMog/pp1KP3uEMcKtqKIwXI+S9do2M6Z7Pyvzp9h6XWz2/v1+VNzvNYJOwiTAdLVzH7fG2NwR4ATU+ua0dEobiVJrJ5bMHO5/rACeUhUa1eYiu16aYJdNaankzWL6hn+qzs4GcejnISBrXwgfOBzylIR8DDt5JYYUGVwv444nM9jfC5rzetd/+JThDQDWKj2CemTmD2ci0NggfaeTQXlemmbQCEDl0nf/vI+DNw7Oifqx1+hHm1VmJSVHKSISqtsw6UHUQ6cBuNMv/isJoP2Nz40jApAtns+AoWV1y2rgsBS9QSf9e2jN17gVzldyqCqw5abho7ikV+n5D67Zm1ResqDMLgD3Lm2ltfbPd/bc6BQ3KP0wPUsArWpUltEkrTYrNtMjdtmTCChaxg/6m17ofsUdE9BUy7+HXhC00MB75RJdeWK4aJFCj3seNMlvbGNfg34hSdyTlYc707YXtPZAg/hS6Y6ge4ry5tRTBhJHatLcLBFBmMKM4dj1lZAf8HZC0ax/he5kF/JI9ZIRcpPHYiMgd+ibY+kezcYvWnlRQUEX81EjKvWKxrqziPs=DUEGBq/66WfaJOzvHolFMJBhLAxbmhMwzbdlm2FFwQrluW1ufyB82ltZs4AQBaRdUnFs5yC4G5E/aLVZKiKUK/XkfYpawf0+UpZj/edPuaK7f5tmjR2Xpgw9JQzNGkr8
  
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Main Repo"
          - ls
          - echo $COMPOSER_AUTH
          - cat ~/.ssh/write-key
