version: 1.3.0

services:
  - composer:
      version: 2

variables:
  global:
    CDE_DEPLOY_POLL_TIMEOUT: 3600
    COMPOSER_AUTH:
      secure: 2acWXcciIYyb8k4jEnWSwRRVAarrpjDmaaLL+Hqsa3Snkru69Xx6DLndKiVy5lGQuckhK+SqQCyOSMZXEibXXZ6kYKoEqNufHRMHT04kGy8U3DtqlZiz0c0SGu4hd9UbH5S4TP1XEeLL4MYqLtEGPUJhHSkLFkk7KehGiAY+p2AeVjRTn7242JC5Sp7iUVOlal3KQp8uJt5/VB+Sy/JUvjGn/eQUpEkCdNuPAFjm9xkqu2kJZrGXi4c1IxYgMjMggqkAn0f/SDep1PrAs/ECXQU9SacUTpmYlIvgtfF+azVWpmWsHSsjn6VxYL7xtyo/5iRUJXBi/nHszsXfks07/BUIybsGN2DjvvfBDHuvOMthJxAv1qFnEw1d0EciLGyDaA184ATsOx/D2ko7xJac1Ad9pCW7NSWbHp+qsKGJKpChedfEzQ8AFk4lahlu8Gz+NMjKgrXa7rjPPVx8lRfkYti95wRKidFQq5CVV2yocP3A2hrk/phXFQc+6T8zKXXjhsHFLjIGTsU3rfaZoqbiJFHUoLGxxXbVu5H0Zl6EVyw4mBDrO5jGSIrrtg0ZhwYxDsrJSc6MOdFXEM8K8p2Cz1NgrFtZYCZCEql+hgO4A8DLCsSmwatV6MnOuXtu/w5/W7c+kinY0uTX48aXg7Ptuei//pzW68m3C+lCvkzMZZPYak=Q7gk9HLyFaRF5BkjqHXhAAyzD3csKG8tHdfxPBHcUCqMcKFuFjCzE4rXi+UiRfuU+hLnRUMShdgADIVX1hG4KP6r4FzRpr/iWE2xO9FFmrICA5jBqsQwOeWUUXy+jaBJNLL30IInK4I4LBuTjysY9IbjVZzjfKVzrtesSJ+dxyVJhM7t72YWcygpgQwM57VGVTpQ0rHhzXwhq3GCZwq70HbEoyljkkdQua7gjUdFyFFObhB2G60+dbIw5oazV2IR5aaVqV52FieDVO/zl+fP+w==
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Composer Install"
          - echo $COMPOSER_AUTH
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - echo "Build completed."
