---
version: 1.0.0
services:
  - mysql
events:
  build:
    steps:
      - behaviors:
          type: script
          script:
            - echo "Setting metadata"
            - pipelines_metadata 'hello' 'world'
            - echo "Executing default event"
            - echo "Creating a long-running background job that should be killed"
            - 'sleep 3700 &'
            - 'jobs -p > /tmp/bg.pid'
            - echo "Testing env vars"
            - 'echo "CI=" : ${CI?"Need to set CI"}'
            - 'echo "CONTINUOUS_INTEGRATION=" : ${CONTINUOUS_INTEGRATION?"Need to set CONTINUOUS_INTEGRATION"}'
            - 'echo "PIPELINE_STATUS=" : ${PIPELINE_STATUS?"Need to set PIPELINE_STATUS"}'
            - 'echo "PIPELINE_ENV=" : ${PIPELINE_ENV?"Need to set ENV"}'
            - 'echo "PIPELINE_APPLICATION_ID=" : ${PIPELINE_APPLICATION_ID?"Need to set PIPELINE_APPLICATION_ID"}'
            - 'echo "PIPELINE_JOB_ID=" : ${PIPELINE_JOB_ID?"Need to set PIPELINE_JOB_ID"}'
            - 'echo "PIPELINE_VCS_PATH=" : ${PIPELINE_VCS_PATH?"Need to set PIPELINE_VCS_PATH"}'
            - 'echo "PIPELINE_DEPLOY_VCS_PATH=" : ${PIPELINE_DEPLOY_VCS_PATH?"Need to set PIPELINE_DEPLOY_VCS_PATH"}'
            - 'echo "PIPELINE_CLOUD_REALM=" : ${PIPELINE_CLOUD_REALM?"Need to set PIPELINE_CLOUD_REALM"}'
            - 'echo "PIPELINE_CLOUD_SITE=" : ${PIPELINE_CLOUD_SITE?"Need to set PIPELINE_CLOUD_SITE"}'
            - 'echo "PIPELINE_GIT_HEAD_REF=" : ${PIPELINE_GIT_HEAD_REF?"Need to set PIPELINE_GIT_HEAD_REF"}'
            - export PERSISTENT_VAR=persistent
            - 'echo "Testing custom ENV vars"'
            - echo $MY_VAR_3
            - echo $MY_VAR_4
            - 'echo "Testing persisting env vars across events"'
            - "echo '{ \"environment\": { \"new_var_1\":\"new_val_1\" } }' > \"${PIPELINES_SCRIPT_DATA_FILE}\""
            - echo "Testing mysql service"
            - mysql -u root -proot -e "show variables like 'max_allowed_packet'"
            - mysqladmin -uroot -proot create test_database
            - "echo 'SHOW DATABASES' | mysql -uroot -proot | grep test_database "
            - 'echo "CREATE TABLE test_table (c1 INT NOT NULL AUTO_INCREMENT PRIMARY KEY, c2 VARCHAR(100));" | mysql -uroot -proot test_database'
            - 'echo "INSERT INTO test_table VALUES (NULL, \"buildsteps\");" | mysql -uroot -proot test_database'
            - 'echo "SELECT * FROM test_table;" | mysql -uroot -proot test_database | grep buildsteps'
            - 'echo "Testing NVM"'
            - nvm --version
            - nvm install v8.11.1
            - nvm use 8.11.1
            - npm install color
            - find . -name ".git" -type d -exec rm -r "{}" +
            - 'echo "Testing Memory Monitor"'
            - pipelines-memory-monitor-status || echo "Could not locate the memory monitor status command"
            - php -i | grep variables_order
            - 'echo "Testing headless chrome browser"'
            - google-chrome --version
            - cd headless-chrome-test && npm install && node_modules/karma-cli/bin/karma start --single-run
      - background-check:
          type: script
          script:
            - 'test -d /proc/$(cat /tmp/bg.pid) && echo "Background job is still running."'
      - variable-across-steps-check:
          type: script
          script:
            - 'echo "PERSISTENT_VAR=" : ${PERSISTENT_VAR?"Need to set PERSISTENT_VAR"}'
      - non-fips-mode-check:
          type: script
          script:
            - 'echo "Check if the default is not FIPS."'
            - kernel=$([ "$(cat /proc/sys/crypto/fips_enabled)" == 1 ] && echo "fips" || echo "not fips")
            - 'echo "Kernel is $kernel enabled."'
            - openssl_var=$([ "$OPENSSL_FIPS" == 1 ] && echo "set" || echo "not set")
            - 'echo "OpenSSL_FIPS env var is $openssl_var to 1."'
            - touch welcome.txt
            - openssl md5 ./welcome.txt || echo 'OpenSSL md5 is not supported in FIPS mode.'
            - node -e "require('crypto').createHash('md5').update('')" || echo 'Node md5 is not supported in FIPS mode.'
            - php -r 'echo md5("foo");' || 'PHP md5 is not working.'
            - rm welcome.txt
      - multiple-ssh-keys:
          type: script
          script:
            - 'echo "Tests multiple SSH keys support"'
            - echo $GIT_SSH
            - cat /home/local/git_workspace_wrapper
            - export PIPELINE_SSH_KEY=~/.ssh/aq-github
            - git ls-remote git@github.com:acquia/pipelines-ui.git
            - export PIPELINE_SSH_KEY=~/.ssh/aq-bitbucket
            - git ls-remote git@bitbucket.org:acquia-pipelines-dev/pipelines-behavior-tests.git
            - unset PIPELINE_SSH_KEY
      - check-ssh-key-access:
          type: script
          script:
            - 'echo "CHECK IF SSH KEYS EXISTS ON BUILD EVENT"'
            - ls -l ~/.ssh
      - check-git-verbose:
          type: script
          script:
            - 'echo "Check if the git clone verbose is working"'
            - git clone --progress --verbose https://github.com/qawoody/welcome-pipelines.git
  post-deploy:
    steps:
      - check-ssh-key-access:
          type: script
          script:
            - 'echo "CHECK IF SSH KEYS EXISTS ON POST DEPLOY EVENT"'
            - ls -l ~/.ssh
      - cat:
         type: script
         script:
         - echo 'Executing post-deploy event'
         - 'echo "new_var_1=" : ${new_var_1?"Need to set new_var_1"}'
      - failing-enable-later:
          type: script
          script:
            - 'echo "Validating validity of container certs"'
            - sudo /usr/sbin/validate_cert /etc/pipelines_config/ssl.cert /etc/pipelines_config/ssl.key

