version: 1.3.0

services:
  - composer:
      version: 2
ssh-keys:
  write-key:
    secure: 2actTPYs4FnR3UqoJt5pP6GuNXdD3+fADdF5tQpIH4yYkKu3d4HxQVAJ37rUBvdJ8VnOdpjE3+yGFPoddOGETOCQb2KbdqXI4STvQPCtyOwoXhbS6dhpy44PY8QU8Mj7JshzWti6/FFRI7iIlvBXDKeyZ1vTg95Hhs8yzJd4xDVHKk+F0uMSX8HTbzgObCVMxN9+1uHpqAW6Do1tOSjmPdPxjn8+P/qi6ttGtWTVRStxuR+hOv5vsrCBni04mIerDC7AHkc+zyL/K7OOzE+XdogAuLytgRR3+kkyWGrlWT7JXenfLaNteX0oDt8oNCDFQzrzH6Rm1aHGlRl21KRc2QBfTXNE7KZWLvyHLEINT26moBL/YYnSW+aPV+sM/quVG36MqNhbEazfhTiQ/aatYKbA2Y+NTttKEwZzKwiEuq+tlaH4no16WmIx0zXFbQxpFLRrnAjFOhNAsBJEGRaO6Q/j8ecz0jxxouMlQ9vHMt9TJ/Yj06kvX/reOL3trXGq9MSYoKHuwuB6UcB6WO0Z88TcuZVhOCJIVUs1z+tij9eeT+W0vy4dAovnLgmhBsSevLp7v8ttr0SUJiefJzDVDXxMoarUQK4uKm9lsEnnWwfNhtVQJxnAm8VIdzqmnD2rw4OcTxhYjil5s/YMwDpl5W/anJLm8TnH0bVRah7OFnynHY=/R0U2ncxJo5HqECLuqhAMpQXjEYEoCw6g/6Zw+RE9wqMovo+j0cwPFdKb/c7i3cF/tgNlBJSYktMhhsJulSfDPtKdz1onJD5zQsseQEKZw6TPnEpL5wu5q6L3HA29Cv224qzbiGC5InXQWaW7H5MFkaHXVvofBAjWEVS8SJhyYMwhk7BE8WUQ9ko2xjGSFfMbHFFG96UDgKCRB0wp/V9/oc2d+YWrsIW0gh7/ldzV+ScRW22DlkaQKbOf1uFGBZLgBhKp7LHhTnVxmhIeJ/UHUWvb+6QWi/ojPxOm8mD/kRfixP2XJ+0Z9JAbdY0+qkNk/LgdAwmkiXLRYf7HQllLWatAXljKiBPHpoBK2gZd7rlCMkqKXyXvkD+PM4E6OtnbeV+IKgu5M9vZfa0AWHBCXCvLD62OMMOIMSOmibRLRgMHF4BzsUJssFxo1+1L5/V9q8g5lOomTZmHsLfteWjBYmsQA/U+r8cW32+bmP+vga5I/yLa9xFZmvWojW2FmZWSBl/PYRaSC3gJ2CI0B4xzEnZLacSseRp9eoW9peRnP2tVWnGWA9PP8rBEpmAyvt3Q+NZNRUxA1Waj+ddVQfUEsJ4SvL9a73I0uPhpilY1ia79LyGi1nOydt7yO0hzwyoBWGFeD3HNnUjLR5LNj7BB6pr5n668akXF9xIJEL/HXA46VFkz5GXTE8w9PagjUlZ

variables:
  global:
    COMPOSER_AUTH:
      secure: 2acY8IL0QIhmVTTxC7mXOzw6m6qtONJc4NTX4eP8nxsr/hBSgX/Lfv2PMMBntSdo9AmlRGVLV1JfiVMoWQM5sBkS4m0wTLJcEewsubFJ9C9/WEksCw3jcYkk8EvvB0ECJgc1JPI/ZUptwC2nE98o8I51rAf2rXFvnOH9+ZB8EJ3ZoLVNKFvll8tN9+FmHD9dhssxnWVvskrxCMfalfUyGmpyD4ds6ke9CY5ZTlOEKaxt781kv5l9z7dkhqk9AWT4pykCG1vGV/Uu+MIjettET4FxCTQoZztUwfrxFNBbEHXsMTDCm12/J4xjgxr8E7UWdJ5RbH68ZtWbWuZXNUxX4zoxYDY3wBQP+K48jqWJ7uW/dIMkfyGevLYqhcuP50SqKkyBff/qcqWwDr9713WE4knA4t7un/6FmmS9GERP8tG9mf/chUwZpY8R75zEa1Hs+7wneCCu6yE2xnvsqNqD4vKdF1EcJ0TirZqONYJvxquKGZH6f0GvGs47jPjw53vie+91B6bfyFRDstWY0Qm93xIcJRRc/a+IhCpz4PMXERoSHfeHrpO22/Yeu8svNayaCUXXhK/AnsIxc8X+Pss4Hk62UReF0vPeoKFQlcY2QRursntStP3Wn4zZuB63lbmSMa1yZOifjl9SBYnL0R5xyB2o2sr7M8OMo6nsEzulW1V0b4=Yh6U6bZJzg3oJ0fSwpImloyGi+dBAiRZXIZ0lMFYUPJtvPxWXZPr3LH90EJzDbyYWv5yJFOX8JpqiPQ8jpK9XSzVKHNy/JYRfmfKiuyfR0ll9kvH//bRhnDTk+33VgNEbFGJLoE/EZ2VvSc585pWgRqbSHEW9FLu86gTjUywB0ETXhD7G1pJF1qbco2RE+OXrcFV7jJx3U2G8aCaSnblBFOnkQ1n/kt0F4Ca/P2tmbFc+DBZHog7ZfsyJQU7HGoQLQxvmh8nQfTwHGGsw/VHQg==
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "Main Repo"
          - ls
          - echo $COMPOSER_AUTH
          - cat ~/.ssh/write-key
