version: 1.3.0

services:
  - composer:
      version: 2

ssh-keys:
  write-key:
    secure: 2acKviMUMqD2ecRh2uTIIAy730wYvT6kFQm+cudoWEUnbDEHNLHwL/WqeSiFqwcqh8r57llRZhieNuPgO1k3qC3loNMUjJsBLObH52gnnJfE/pSUbDIAVTMJAUQuO/lAV4M7mSlUWbaLXPxHVbHexd4k617Ls59UWJCbo5XW3K0RLGzTpegt8NDtrWndvxazWHS3ib9BrzdYYYN3/ZHIDAefUlt4f9ma6c2tzBHgZSz6a5MfJNJvzFimjvnPK0LOcoFNINzxj/ZadnzNDExHYGHmhfaNl0IguuU7KOpn/fk3NHhT22+XpXC954NQIj9mfELLTwZBLGHXnjy65/qXPI2gT1lxwy08/Oz1gNKOzITCXe1bq3MOud1QKtSQnvctoaaQPjkhdetZu30Y4r00frIBIq7DG/i8E5QHpc58dZs/fpy2phJ5ejlchi4CLjLKUSDmTR0+880NACJTzviuoilwrYTkRQljEMYLusm3I/amY/4YQVryVV4FDWMyG+LmCDXPaXl0HdUFWbnmH6dfrWgN5CYagCA60LlVwRi8oErPI5g36NiKCrJW60+SJkWVHKwW9tlNeUzU03PDvMnwrFEHxBqQPPKoCKU8RL4T2UvJzZRdKS0pLly4jsvK5mWI2S2t3hBbHwXEjtkiyQ0D1vKIqePaZsK+QjZcmrOMoSYLAQ=OA03z5sYCn56LiefX2q2Ros3FktJCgWr7KC4Ta5EZsC330pVOK/R18tr84oNWGYJu9z2X6N1mBSKSnIA+sefv2Qo+yybvdfJdmuZPVFsTCKdKIKLLQnEwGjoy/8IYQ1xZMQ6F6rcz5z9Jb8yAHb4xlqUbvIJiBg1SfSkX033lera6nP3RU/PDgqWub1VrcEEPu0fHKkuWLbfxvCWm4FYd3WEY6r9LGVFih0gofS9ApJVH7Ls8Qz7ijOJ4LGXqXI9vb+c4ZnEDqTOY3hT1F0/E27sHivNZb1BZoqcsw5EVsHERuwV+56BAFwH/22FaHI1veV5glKqCV30/PhqYtOWFztGxyrovGXYL00/gqrsU75BN7MjRtIguSXPXZVZ9L/IFj/e0oIRsXjVmicgqsXCsovIi0vgR5ZfwfLTUzXrf+6i/ayn4dQc54E31wHLLj7s7wtyFRisrIuCDeGkOaPZuJogGgf+XjgPf7TGOhgCWhNcF9PluJkeKoX/qLi+6HvMGUrrCXHdRQaSFzjh88779UzUBAtS4Ik7GEfookTBe3ni/av3AC5EaGYaghn4zXREJCTHEQsU21vE/HWLu1Ia5Cy1uzNse9YP8xHSi7iQtppOKgn85OiqIVVsRPzCqe7rJ3WmFNkXCb6ibgEOFr5qYHLE2M4D4WkywvOxxUkHwH8=

variables:
  global:
    VARIABLE_1:
      secure: 2acHm9uaqUsUtSH/dRNR4Z1GwUvPBGXxCdgDmoiw4MtVCogidE/z830YRSZUn4c3qjym10fXFh0dehuzgXljACGK2djcgLPxQK0k2pFhFwC3ADaPrCrvJS9ABDJJIQaknfCCvarIWF9uFH75UV7FzkQ9HmnY+amKLxhXkbCRZQadR6kw1L0TQG4c/IfDDNC8on8Fx6zxOwKV/y3ZyCoNh/c5fjDGkDBawaRVSPs9JEApAeTCHVo+XUtftVeyAcVgu7Vu9OuXr2fR5wcl2ftDJlDKxtw0f9YQFqjym9rwp1qnbtJH/frRVgs/A0r40tKJ4BOQNqUmNJcwO5m9qCE9vQCtLQhnUYqaCTfUWcYLJOLJEZYWLoQfxvsw3RnzaPNU9F1DOtdluer3FRCc7pAw30LL+IAE+qDORPZqwft7Iwzh5Ui/anvC8arIvPLD0ENQoLI4IBTbCD4rcIitxX2xVtoG2jW4MQtTk4//IQsL1cfJ6WVpaMbEvsID3NMhYoHcIZ7Yl6MFxNlHawlqtJdS+2gUIhmkd9cxN50jFPeuqYjsQtxDSKuXKnU7eX8rFdYudBTIIYHdfZ/cjg7bs/5o28DHgwElzhnjANO1AVAECv+WKojJbOTslqf8HLqU4o22nIfsCew30q3N8gMGP2G272tVKPNpEWbruOYYgwmNvEEurQ=nCd7baK0E7fZ7u2cWGADcyh29ZNjF2z9q5MhTlgoEn8MkvN+4fWgEWyff5OgTvyXFkFfxlpRBjyFrY6KDieii6VCISEys7UbbDplbviLOIyjoh9GH88ekWLQD8GsrXSl

events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
          - echo "test decrypt"
          - ls
          - echo $VARIABLE_1
          - echo "printing ssh key"
          - cat ~/.ssh/write-key
